FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY . .
RUN dotnet workload install maui-android
RUN dotnet restore InventoryManager.Maui/InventoryManager.Maui.csproj
RUN dotnet build InventoryManager.Maui/InventoryManager.Maui.csproj -c Release --no-restore
