<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>InteriorInventory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2612" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.7" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="InteriorInventory.Android/**/*.cs" />
    <None Remove="InteriorInventory.Android/**/*" />
  </ItemGroup>
</Project>
